### ISSUE TITLE
Add usage notes to README

### ISSUE THREAD

**Issue by tvercaut** [cai4cai/sha1inbrowser#7]
The content of the [word document](https://emckclac-my.sharepoint.com/:w:/g/personal/k2036562_kcl_ac_uk/EVKef5Nx52dMs190u-1aR30B9JpkOoLWWnmLpxve_l9pOw?e=Bd31TD&xsdata=MDV8MDJ8dG9tLnZlcmNhdXRlcmVuQGtjbC5hYy51a3wxMGJjNTU3OWJlZWM0NjY4NGY5MzA4ZGM1ZmJlOGUyM3w4MzcwY2YxNDE2ZjM0YzE2YjgzYzcyNDA3MTY1NDM1NnwwfDB8NjM4NDkwNTE5MjQ4NzI1MDU0fFVua25vd258VFdGcGJHWnNiM2Q4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazFoYVd3aUxDSlhWQ0k2TW4wPXwwfHx8&sdata=MjFNVFhzVUd1dlRGQjRrV2Q1ajRLS2JreFFhbHNJZDAzK0QzYm9mbGtmRT0%3d) prepared by @theo-barfoot  should be ported to the README.

**Comment by theo-barfoot** [comment]
Done, implemented in [549af72](https://github.com/cai4cai/sha1inbrowser/commit/549af72a5705bdbfd60d7ef4aa741c50bd2bc181)
